#version: '2.1'
#
#services:
#  retina:
#    container_name: retina_train
#    image: retina_train:1.0
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
#    restart: always
#    runtime: nvidia
#    ports:
#      - "3333:22"
#
#    volumes:
#      - /mnt/sda1/facility_images/:/data_sda1
#      - /tmp/.X11-unix:/tmp/.X11-unix
#    network_mode: host
#
#

version: '2.1'

services:
    db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    web:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - "5000"
        networks:
            - frontend
            - backend
        volumes:
            - /mnt/sdb1/arman_scripts/mlflow/mlruns/:/mlruns
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root file:/mlruns --host 0.0.0.0

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata: